# action.yml
name: 'Promtool GitHub Actions'
description: 'Run promtool commands against Prometheus rules files'
author: 'Praveen'
inputs:
  cmd:
    description: 'The promtool command to run'
    required: true
    default: false
  files:
    description: 'Files regex for prometheus rules files'
    required: true
    default: false

runs:
  using: 'docker'
  image: 'Dockerfile'
